name: Build Supermodel for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install MSYS2, GCC, Make, and SDL dependencies
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: |
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-SDL2_net

      - name: Show installed binaries for debugging
        run: |
          echo "Installed in /mingw64/bin:"
          ls /mingw64/bin | grep -E 'gcc|make|SDL2'

      - name: Build Supermodel (without network)
        shell: msys2 {0}
        run: |
          set -e
          echo "Running build command..."
          mingw32-make -f Makefiles/Makefile.Win32 > build.log 2>&1 || (
            echo "::error::Build failed. Dumping build.log..." &&
            cat build.log &&
            exit 1
          )

      - name: Upload binary
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Supermodel-Windows
          path: Supermodel.exe

      - name: Upload build log if failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log
